# Generated by Django 6.0.4 on 2026-07-15 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="feed",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="feed.feeds",
            ),
            preserve_default=False,
        ),
    ]
