# Generated by Django 5.2.4 on 2026-07-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_comments_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='nickname',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feeds',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='nickname',
            field=models.CharField(max_length=6),
        ),
    ]
