# Generated by Django 4.2.8 on 2026-07-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_comments_nickname_alter_feeds_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
