# Generated by Django 4.2.8 on 2026-07-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_burncount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at']},
        ),
    ]
